### ISSUE TITLE
column names should be alphanumeric

### ISSUE THREAD

**Issue by adrianbr** [scale-vector/dlt#36]
a best practice for table and column names is to keep them as aphanumeric with underscores.

Each database system may support quoted special characters in column names to some extent, but it is best to avoid them.

A solution could be converting "illegal" characters into a numeric code.

example: <class 'google.api_core.exceptions.BadRequest'>
400 Illegal field name: stats__execution__num_by_latency__<_1

**Comment by rudolfix** [comment]
100% agree this is a bug.... the naming functions are pluggable, right now I use something that converts names to snake case and removes some of the characters. I will just keep the ascii and underscores. naming will be lower cased.

people can write their own naming module if they wish
